language: php

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
    - TASK_STATIC_ANALYSIS=0
    - TASK_TESTS_COVERAGE=0

matrix:
  include:
    - php: "7.4"
      env:
        - TASK_STATIC_ANALYSIS=0 # set to 1 to enable static analysis
        - TASK_TESTS_COVERAGE=1

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug is not installed"

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install $DEFAULT_COMPOSER_FLAGS
  - |
    if [ $TASK_STATIC_ANALYSIS == 1 ]; then
      pecl install ast
    fi

before_script:
  - php --version
  - composer --version
  # enable code coverage
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
        PHPUNIT_COVERAGE_FLAG="--coverage-clover=coverage.clover"
    fi

script:
  - phpdbg -qrr vendor/bin/phpunit --verbose $PHPUNIT_COVERAGE_FLAG
  - |
    if [ $TASK_STATIC_ANALYSIS == 1 ]; then
      composer phan
    fi
  - |
    if [ $TASK_STATIC_ANALYSIS == 1 ]; then
      cat analysis.txt
    fi

after_script:
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi


notifications:
  slack:
    -
      rooms:
        -
          secure: bMwbLe0dn8b9IEoZ7yEP/Ag3AzWo9U0leZDcmdyFmOjVgK8m/GgJzFJ837b4qTuS6h3WtICwMcsi2s0rvaXFbk0ibzUs31Atx8A0MRxXlCUku2vWZCjqq83MVUVedMd6vS7L40AVd0hwPGiAmdx1Qy8up6rI5fuXj/mAlfH92P+DGNbG5ovukNkGNHwCSJeV/DvRyF5PbOjISgnuCx9UWYCwc2ieV757z/ijuIlznHb7tUC1TbI8bz1tC/fjZjsaN9h0muUD+TyD/wXLMfQpk3cy8uTXW63h/WACTPFWmJvLdKcCMGV2sBsbs2akAEnzwfP+7Rzy/4x3iw8Q3zx6LD3zpw5+StjmJ0eIypIEhutysWSVermQAFAPgHXapZNhGotMjMKuSshBgyUYhXahM+fjr/XygatpvyM+xRrNLbD/i3hg1t/P9h3y8R5TKB4xMrSn5hC3wU/zssf3gJYSn2qZO7yva9cy9oANj/OPNogmVnajSaytSzv2YkVbSh+Gkp3olXHsUkd6ZOoJBRq5zH7ShM71/wuJJ7cXhaMgw+4J1ApDFRwINcijNAzfvoBy1i63wiu/nihznGHcmdPAV143s/qkcrnoS/wtGKNzJy4WBYJ9G4HFGbEq9uNJvQnFLMJFjMdoKswLLJTzQcU7xzOuyO2tdtVBmpjlKDKUMOg=
      on_success: always
      on_failure: never
      on_pull_requests: false
    -
      rooms:
        -
          secure: AamS+67y+rvB/qX7o0G7bdzHhaflgX85kab6a8rfL4UCgwIC9LrDgvXGS75hTcE0jl28aG+qvjC/4C+xp0MWu9E/jN7u39zexuYKXk7qhXBgfFs9BoTZM0iuMVhrxW+jN/S/FoD+g3hNxSVR6R8ku76Zf6YKqeHoT7IlDfsP2He8uxeX2zKd/hKOfkNW6DPCSAj2ncQkZKbWivKfai7275vtpH7CUO+GyC7FtasHYuAGYe5u6imvlcSUsGby2l293dxyKwDLrVIeGPE793CZ7wfMoU18ASvAwhTKSo09YMJ+kvoCTIrzkKa7WAF9svw8+oMto0JtjFOZaGW8rJtfHCZL3DguIl/3pwrjMrnKDVC73VfdE2af4nGCVfWbT859IDCbpbwC+s97QVJ2ZIrpybGu9nEBc9/BOg22g3uppE3+gQp775cCsInhwgji+npB0WMleH1d6J2dEv7iKOIKZGzGas4fq6pUeV+vUrLsLpgxroMG4cTTCkM04MnVd0NP63ocBSUr1Jo/qn7cXNTIxU4tbFPn5p5UqfWV5SK59az26RiBGmRKtIcisN8W0GWqoKTP2XoW1ZE7NdtHw/CntY3Z7bft92Mb9hBLgcgj+wqwPqQx3IDaeBQd4HMiRylmFVZ0Vk66Zh9k2pYgVgsWtZ0o/KyqHCUI/LcLY4oNIuo=
      on_success: never
      on_failure: always
      on_pull_requests: false
